### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 0xC4aE1e5** [avysis/avysis#1]
- [ ] Remove virus dialog instead of individual message boxes
- [ ] Use jobs instead
- [ ] VirusTotal (possibly a proxy to howtoremove.guide) or retry every time
- [ ] Proper real-time protection
